import './globals.css';
import { Inter } from 'next/font/google';
import { ApolloWrapper } from '@/lib/apollo-provider';
import Navbar from './components/Navbar';
import Provider from '@/lib/client-provider';
import { getServerSession } from "next-auth/next";
import { authOptions } from './api/auth/[...nextauth]/authOptions';


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {

  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>
          <ApolloWrapper>
            <div className='min-h-screen text-slate-800'>
              <Navbar />
              <main className='mx-auto p-7'>
                {children}
              </main>
            </div>
          </ApolloWrapper>
        </Provider>
      </body>
    </html>
  );
}